// <auto-generated />
namespace DAL.Web.Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class wff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wff));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050927238_wff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
